### ISSUE TITLE
Bookmark issue

### ISSUE THREAD

**Issue by rmdes** [jamesvandyne/tanzawa#116]
When I try to add a new Bookmark in my localhost installation (still testing tanzawa)
I get this error : 

`[07/Nov/2021 10:25:52] "GET /a/bookmark/create/ HTTP/1.1" 200 1880
Internal Server Error: /a/bookmark/meta_info/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/app/apps/entry/views.py", line 185, in form_valid
    linked_page = extract_reply_details_from_url(form.cleaned_data["url"])
  File "/app/apps/indieweb/extract.py", line 44, in extract_reply_details_from_url
    data = extruct.extract(response.text)
  File "/usr/local/lib/python3.8/dist-packages/extruct/_extruct.py", line 108, in extract
    output[syntax] = list(extract(document, base_url=base_url))
  File "/usr/local/lib/python3.8/dist-packages/extruct/rdfa.py", line 154, in extract_items
    jsonld_string = g.serialize(format='json-ld', auto_compact=not expanded).decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'`

**Comment by jamesvandyne** [comment]
That appears to be crashing because of an error with extruct, a dependency library. It looks like there was a newer version, 0.13.0 released a couple of months ago that _may_ fix the issue. Upgrading should just be a matter of changing [this line](https://github.com/jamesvandyne/tanzawa/blob/2773dd3577c705e69ee9ff946b695e3c0135f022/requirements.lock#L18) to 0.13.0 and rebuilding the image.

**Comment by jamesvandyne** [comment]
I got reports that this issue was fixed with an upgrade to extruct. As I've updated the requirements.lock, the issue should be fixed. Let me know if you're still running into this.
